fix typos for fmri-preprocessing-tutorial.md
brainlife/docs pull request #115
Opened 2023-12-01 15:47 UTC by bendichter

2023-12-01 16:10 UTC, bendichter commented on docs/tutorial/fmri-preprocessing-tutorial.md
> -
Attempting to fix this formatting error:

<img width="696" alt="image" src="https://github.com/brainlife/docs/assets/844306/6e16d44a-d326-4de9-beb1-e8bcd60b5c35">

2023-12-04 15:05 UTC, francopestilli requested changes
thanks @bendichter a few comments and changes @anibalsolon

2023-12-05 13:32 UTC, bendichter commented on docs/tutorial/fmri-preprocessing-tutorial.md
> +The first step of diffusion preprocessing often involves processing the anatomical images. In order to guarantee that any generalizations regarding location made from the preprocessed diffusion data
The name of the app is "(T1)". Maybe it should be "(T1w)", but my goal here is to ensure that the name in the tutorial matches the name of the app.

2024-02-26 19:18 UTC, anibalsolon commented on docs/tutorial/fmri-preprocessing-tutorial.md
> +The first step of diffusion preprocessing often involves processing the anatomical images. In order to guarantee that any generalizations regarding location made from the preprocessed diffusion data
Better keep as T1 indeed!

2024-02-26 19:19 UTC, merged